const data = [
  {
    category: "pizza",
    Product_ID: "A11",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Rau Củ (Xốt Bơ Tỏi)",
    Product_Name_EN: "Veggie Supreme (Garlic-Parsley Butter Sauce)",
    Product_Description_VN:
      "Thanh Nhẹ Với Ô Liu Đen Tuyệt Hảo, Cà Chua Bi Tươi Ngon, Nấm, Thơm, Bắp, Hành Tây Và Phô Mai Mozzarella Cho Bạn Bữa Tiệc Rau Củ Tròn Vị",
    Product_Description_EN:
      "Black Olives, Fresh Cherry Tomatoes, Mushrooms, Pineapples, Sweet Corns, Onions On Top Of Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Rau_Cu_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Rau_Cu_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "A11",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "A28",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Gấp Đôi Nhân Phủ Hải Sản Xốt Pesto",
    Product_Name_EN: "Double Topping Seafood Pesto Pizza",
    Product_Description_VN:
      "Pizza Hải Sản Xốt Pesto Với Hải Sản (Tôm, Mực) Nhân Đôi Cùng Với Nấm Trên Nền Xốt Pesto Đặc Trưng, Phủ Phô Mai Mozzarella Từ New Zealand Và Quế Tây.",
    Product_Description_EN:
      "Double Topping Of Seafood (Shrimp, Squids) With Sliced Mushrooms, Our Signature Pesto Sauce, Perfectly Melted Mozzarella Cheese From New Zealand, Topped With Fresh Basil.",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Gap_Doi_Nhan_Phu_Hai_San_Xot_Pesto_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Gap_Doi_Nhan_Phu_Hai_San_Xot_Pesto_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "A28",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "A29",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Gấp Đôi Nhân Phủ Cơn Lốc Hải Sản",
    Product_Name_EN: "Double Topping Ocean Delight Pizza",
    Product_Description_VN:
      "Pizza Cơn Lốc Hải Sản Với Hải Sản (MựC, Thanh Cua) Nhân Đôi Cùng Với Thơm, Ớt Chuông Xanh, HàNh Tây, Phủ Phô Mai Mozzarella Từ New Zealand Trên Nền XốT Cheesy Mayo.",
    Product_Description_EN:
      "Double Topping Of Seafood (Squid, Crabsticks) With Pineapple & Green Capsicum, With Cheesy Mayonnaise Sauce And Perfectly Melted Mozzarella Cheese From New Zealand.",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Gap_Doi_Nhan_Phu_Con_Loc_Hai_San_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Gap_Doi_Nhan_Phu_Con_Loc_Hai_San_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "A29",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "A30",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Gấp Đôi Nhân Phủ Hải Sản Xốt Tiêu Đen",
    Product_Name_EN: "Double Topping Seafood Black Pepper Pizza",
    Product_Description_VN:
      "Pizza Hải Sản Xốt Tiêu Đen Với Hải Sản (Tôm, Mực, Thanh Cua) Nhân Đôi Cùng Với Hành Tây, Thơm Phủ Xốt Tiêu Đen Thơm Nóng Và Phô Mai Mozzarella Từ New Zealand.",
    Product_Description_EN:
      "Double Topping Of Seafood (Shrimp, Squids, Crabsticks) Combined With Pineapple And Sliced Onions, Black Pepper Spicy Sauce And Perfectly Melted Mozzarella Cheese From New Zealand.",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Gap_Doi_Nhan_Phu_Hai_San_Xot_Tieu_Den_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Gap_Doi_Nhan_Phu_Hai_San_Xot_Tieu_Den_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "A30",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "AD09",
    Product_type: "HNH",
    Product_Name_VN: "PIZZA VIỀN PHÔ MAI 2 LOẠI NHÂN PHỦ (CỠ VỪA)",
    Product_Name_EN: "CHEESE CRUST HALF & HALF PIZZA (REGULAR)",
    Product_Description_VN:
      "Cùng thưởng thức 2 loại nhân phủ thơm ngon trên cùng 1 bánh pizza. Pizza Half Half - vị ngon nhân đôi.",
    Product_Description_EN:
      "Trying the 2 different favors of topping at the same time with Pizza Half & Half, the fulfillment of taste just in 1 pizza.",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hai_Vi_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Half_Half_Co_Vua_400_275.jpg.jpg",
    Product_Discount: "true",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "AD09",
    POS_NAME: "H&H REGULAR",
    FilterCondition: "<=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "AD10",
    Product_type: "HNH",
    Product_Name_VN: "PIZZA VIỀN PHÔ MAI 2 LOẠI NHÂN PHỦ (CỠ LỚN)",
    Product_Name_EN: "CHEESE CRUST HALF & HALF PIZZA (LARGE)",
    Product_Description_VN:
      "Cùng thưởng thức 2 loại nhân phủ thơm ngon trên cùng 1 bánh pizza. Pizza Half Half - vị ngon nhân đôi.",
    Product_Description_EN:
      "Trying the 2 different favors of topping at the same time with Pizza Half & Half, the fulfillment of taste just in 1 pizza",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hai_Vi_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Half_Half_Co_Lon_400_275.jpg.jpg",
    Product_Discount: "true",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "AD10",
    POS_NAME: "H&H LARGE",
    FilterCondition: "<=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C02",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Hải Sản Xốt Pesto",
    Product_Name_EN: "Seafood Pesto",
    Product_Description_VN:
      "Tôm, Mực Và Nấm Trên Nền Xốt Pesto Đặc Trưng, Phủ Phô Mai Mozzarella",
    Product_Description_EN:
      "Shrimp, Squid And Mushrooms On A Bed Of Signature Pesto Sauce, Topped With Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hai_San_Xot_Pesto_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hai_San_Xot_Pesto_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C02",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C03",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Thịt Và Xúc Xích",
    Product_Name_EN: "Supreme Meat Lover's",
    Product_Description_VN:
      "Thơm Ngon Và Giàu Protein Với Thịt Xông Khói, Xúc Xích, ThịT Bò, Giăm Bông Và Pepperoni",
    Product_Description_EN:
      "Enjoy A Tasty, Protein-Packed Serving Of Bacon, Sausage, Beef, Ham And Pepperoni",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Thit_Va_Xuc_Xich_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Thit_Va_Xuc_Xich_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C03",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C04",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Hải Sản Xốt Tiêu Đen",
    Product_Name_EN: "Seafood Black Pepper",
    Product_Description_VN:
      "Tôm, Mực, Thanh Cua, Hành Tây, Thơm Phủ Xốt Tiêu Đen Thơm Nóng Và Phô Mai Mozzarella",
    Product_Description_EN:
      "Shrimps, Squids, Pineapples, Crabsticks, Onions On A Bed Of Hot Black Pepper Sauce And Topped With Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hai_San_Xot_Tieu_Den_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hai_San_Xot_Tieu_Den_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C04",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C05",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Thập Cẩm",
    Product_Name_EN: "Supreme",
    Product_Description_VN:
      "Mang Hương Vị Truyền Thống Với ThịT Bò, Thịt Xông Khói, Pepperoni, Ớt Chuông, Nấm Và Hành Tây, Phủ Phô Mai Mozzarella",
    Product_Description_EN:
      "Traditional Pizza With Beef, Bacon, Pepperoni, Capsicums, Mushrooms, Onions And Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Thap_Cam_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Thap_Cam_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C05",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C06",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Pepperoni",
    Product_Name_EN: "Pepperoni",
    Product_Description_VN: "Pepperoni Với Phô Mai Mozzarella Tuyệt Hảo",
    Product_Description_EN: "Pepperoni With Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Xuc_Xich_Nuong_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Xuc_Xich_Nuong_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C06",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C07",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Cơn Lốc Hải Sản",
    Product_Name_EN: "Ocean Delight",
    Product_Description_VN:
      "Mực, Thanh Cua, Thơm, Ớt Chuông Xanh, HàNh Tây Và Phô Mai Mozzarella Trên Nền Xốt Cheesy Mayo Và Phô Mai Mozzarella Thượng Hạng",
    Product_Description_EN:
      "Squids, Crab Sticks, Pineapples, Capsicums On Top Of Cheesy Mayo Sauce And Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Con_Loc_Hai_San_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Con_Loc_Hai_San_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C07",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C08",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Gà Nướng Nấm",
    Product_Name_EN: "Chicken Deluxe",
    Product_Description_VN:
      "Pizza Gà Nướng Nấm Trong Cuộc Phiêu Lưu Vị Giác Với Thịt Gà, Nấm, Thơm, Cà Rốt Và Rau Mầm Phủ Xốt Tiêu Đen Thơm Nồng",
    Product_Description_EN:
      "Chicken Deluxe Pizza With Chicken Breast, Mushroom, Pineapple, Carrot And Cress Layered On Top Of Our Black Pepper Sauce",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Ga_Nuong_Nam_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Ga_Nuong_Nam_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C08",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C09",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Cá Ngừ",
    Product_Name_EN: "Fisherman's Tuna",
    Product_Description_VN:
      "Mang Hương Vị Biển Cả Nhẹ Nhàng Với Cá Ngừ, Thanh Cua, HàNh Tây, Thơm Trên Nền Xốt Pesto",
    Product_Description_EN:
      "Fisherman'S Tuna Pizza Bring You The Dedicate Taste Of The Ocean With Tuna, Crab Sticks, Onions, Pineapples On Top Of Pesto Sauce",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Ca_Ngu_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Ca_Ngu_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C09",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C11",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Hawaiian",
    Product_Name_EN: "Hawaiian Paradise",
    Product_Description_VN:
      "Phủ Giăm Bông Và Thơm Ngọt Dịu Trên Nền Sốt Cà Chua Truyền Thống",
    Product_Description_EN: "Hawaiian-Flavored Pizza With Hams And Pineapples",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hawaiian_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Hawaiian_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C11",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C12",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Phô Mai Cao Cấp",
    Product_Name_EN: "Cheese Lover",
    Product_Description_VN: "Với 3 LớP Phô Mai Mozzarella VàNg ÓNg Quyến Rũ",
    Product_Description_EN:
      "A Triple-Layer Of Mozzarella Cheese On Top Of Tomato Sauce",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Pho_Mai_Cao_Cap_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Pho_Mai_Cao_Cap_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C12",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C13",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Tôm Xốt Bơ Tỏi",
    Product_Name_EN: "Shrimp Scampi",
    Product_Description_VN:
      "Với Tôm, HàNh Tây Và Ớt Chuông Phủ Trên Nền Xốt Bơ Tỏi",
    Product_Description_EN:
      "Shrimps, Onions, Capsicums On Top Of Garlic-Parsley Butter Sauce",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Tom_Xot_Bo_Toi_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Tom_Xot_Bo_Toi_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C13",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C21",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Rau Củ (Xốt Cà Chua)",
    Product_Name_EN: "Veggie Supreme (Tomato Sauce)",
    Product_Description_VN:
      "Thanh Nhẹ Với Ô Liu Đen Tuyệt Hảo, Cà Chua Bi Tươi Ngon, Nấm, Thơm, Bắp, Hành Tây Và Phô Mai Mozzarella Cho Bạn Bữa Tiệc Rau Củ Tròn Vị",
    Product_Description_EN:
      "Black Olives, Fresh Cherry Tomatoes, Mushrooms, Pineapples, Sweet Corns, Onions On Top Of Mozzarella Cheese",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Rau_Cu_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Rau_Cu_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C21",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "C23",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Bò BBQ Xốt Cay Hàn Quốc",
    Product_Name_EN: "Korean BBQ Spicy Beef",
    Product_Description_VN:
      "Thịt Bò Úc, Thơm Trên Nền Xốt Hàn Quốc Cay Nồng, Phủ Rau Mầm Và Mè Rang",
    Product_Description_EN:
      "Beef, Pineapples, Sprouts, Sesames In Korean Spicy Sauce Base",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Bo_BBQ_Xot_Cay_Han_Quoc_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Bo_BBQ_Xot_Cay_Han_Quoc_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "C23",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "FQ001",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Go Bò Xốt Tiêu Đen",
    Product_Name_EN: "Pizza Go Black Pepper Beef",
    Product_Description_VN:
      "Bò Nướng Kết Hợp Với Hành Tây, Ớt Chuông Nướng Trên Nền Sốt Tiêu Đen, Phủ Phô Mai Mozzarella Và Lá Quế Tây, Cuộn Tròn Trong Lớp Bánh Pizza Đặc Trưng Của Pizza Hut. ",
    Product_Description_EN:
      "Grilled Beef Combined With Onions, Bell Peppers On Black Pepper Sauce, Topped With Mozzarella Cheese And Fresh Basil Leaves, Rolled In Pizza Hut'S Signature Pizza Dough",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Go_Bo_Xot_Tieu_Den_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Go_Bo_Xot_Tieu_Den_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "FQ001",
    POS_NAME: "PG_BEEF PEPPER",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "FQ002",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Go Thịt Xông Khói",
    Product_Name_EN: "Pizza Go Bacon",
    Product_Description_VN:
      "Thịt Xông Khói Nướng Giòn, Hành Tây, Dứa Chua Ngọt Trên Nền Sốt Phô Mai Đặc Trưng, Phủ Phô Mai Mozzarella Rồi Được Cuộn Tròn Trong Lớp Bánh Pizza Đặc Trưng Của Pizza Hut.",
    Product_Description_EN:
      "Crispy Bacon, Oven-Baked Onions And Sweet&Sour Pineapple On Bed Of Signature Cheesy Sauce, Topped With Mozzarella Cheese Then Rolled In Pizza Hut'S Signature Pizza Dough.",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Go_Thit_Xong_Khoi_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Go_Thit_Xong_Khoi_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "FQ002",
    POS_NAME: "PG_BACON",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
  {
    category: "pizza",
    Product_ID: "FQ003",
    Product_type: "pizza",
    Product_Name_VN: "Pizza Go Gà Xốt Pesto",
    Product_Name_EN: "Pizza Go Creamy Pesto Chicken",
    Product_Description_VN:
      "Thịt Gà, Hành Tây, Nấm Và Bắp Ngọt Trên Nền Sốt Pesto, Thêm Chút Tiêu Đen Thơm Nồng Quện Trong Phô Mai Mozzarella, Cuộn Trong Lớp Bánh Pizza Đặc Trưng Của Pizza Hut. ",
    Product_Description_EN:
      "Grilled Chicken, Oven-Baked Onions, Mushroom And Sweet Corn On A Pesto Sauce Base Mixed With Black Pepper, Covered By Melted Mozzarella Cheese Then Rolled In Pizza Hut'S Signature Pizza Dough.",
    Product_Photo:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Go_Ga_Xot_Pesto_400x275.jpg",
    Product_Photo_2:
      "https://cdn.pizzahut.vn/images/Web_V3/Products/Pizza_Go_Ga_Xot_Pesto_320x590.jpg",
    Product_Discount: "false",
    Original_price: "0",
    Sale_price: "0",
    Display_price: "0",
    POS_ID: "FQ003",
    POS_NAME: "PG_CHICKEN PESTO",
    FilterCondition: "=",
    PromotionItem: "false",
    PromotionItemIcon: null,
    PromotionItemTNC_EN: null,
    PromotionItemTNC_VI: null,
    in_dex: "1",
  },
];
export default data;
